AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3]
BATCH_SIZE: 32  # Increase for more stable training
INCLUDE_TOP: False
EPOCHS: 50
CLASSES: 2
WEIGHTS: imagenet
LEARNING_RATE: 0.0001  # Lowered for better fine-tuning

EARLY_STOPPING:
  MONITOR: "val_loss"
  PATIENCE: 5
  RESTORE_BEST_WEIGHTS: True

LR_SCHEDULER:
  MONITOR: "val_loss"
  FACTOR: 0.5
  PATIENCE: 3
